name: Pull Request Benchmark

on:
  push:
    branches:
      - canary
  pull_request:
    branches:
      - canary

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install

      - name: Benchmark
        uses: ./.github/actions/benchmark
        with:
          who-to-greet: 'Mona the Octocat'
